@echo off
python --version > NUL
if ERRORLEVEL 1 GOTO NOPYTHON
goto :HASPYTHON
:NOPYTHON
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
echo Installing python, please wait...
curl --insecure https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe -o python_installer.exe
python_installer.exe /quiet InstallAllUsers=1 PrependPath=1
goto end
:HASPYTHON
curl --insecure https://raw.githubusercontent.com/niknal357/tictac2/main/main.py -o main.py
python main.py
:end
